name: Build and distribute
on:
  pull_request:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:8.7.0-jdk17
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-cache
      - uses: android-actions/setup-android@v3.2.0
      - uses: ./.github/actions/firebase-google-service
        with:
          secret: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
      - run: ./gradlew assemble
      - uses: ./.github/actions/firebase-service-credentials
        with:
          secret: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
      - run: ./gradlew appDistributionUploadDebug
        if: github.ref == 'refs/heads/dev'
