name: Dev branch verification
on:
  push:
    branches:
      - dev

jobs:

  build:
    uses: ./.github/workflows/setup_docker_and_execute_command.yml
    with:
      command: ./gradlew build
    secrets: inherit
