name: Dev branch verification
on: pull_request
#  push:
#    branches:
#      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:8.0.0-jdk17
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10
      - name: Save google-service.json
        env:
          FIREBASE_GOOGLE_SERVICE: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
        run: echo $FIREBASE_GOOGLE_SERVICE > app/src/google-services.json
      - name: Save service-credentials.json
        env:
          FIREBASE_SERVICE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
        run: echo $FIREBASE_SERVICE_CREDENTIALS > app/src/service-credentials.json
      - name: Build
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk

  upload-debug-apk:
    runs-on: ubuntu-latest
    container: gradle:8.0.0-jdk17
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10
      - name: Save google-service.json
        env:
          FIREBASE_GOOGLE_SERVICE: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
        run: echo $FIREBASE_GOOGLE_SERVICE > app/src/google-services.json
      - name: Save service-credentials.json
        env:
          FIREBASE_SERVICE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
        run: echo $FIREBASE_SERVICE_CREDENTIALS > app/src/service-credentials.json
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: apk
      - name: Distribution upload
        run: ./gradlew appDistributionUploadDebug
