name: Dev branch verification
on:
  push:
    branches:
      - dev

jobs:
  build:
    steps:
      - name: Build
        uses: ./.github/workflows/setup_build_environment.yml
        with:
          command: ./gradlew build
        secrets: inherit
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk

  upload-debug-apk:
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: apk
      - name: Distribution upload
        uses: ./.github/workflows/setup_build_environment.yml
        with:
          command: ./gradlew appDistributionUploadDebug
        secrets: inherit
