name: Dev branch verification
on:
  push:
    branches:
      - dev

jobs:

  build:
    uses: ./.github/workflows/setup_build_environment.yml
    with:
      command: ./gradlew build
    secrets: inherit
