name: Ktlint
on: pull_request
jobs:
  ktlint-check:
    runs-on: ubuntu-latest
    container: gradle:8.4.0-jdk17
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-cache
      - run: ./gradlew ktlintCheck
