name: Metadata
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  assert-pull-request-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Assert branch name
        run: python ./.github/scripts/branch/assert_branch_name.py ${{ github.head_ref }}
      - name: Assert commit message
        run: |
          HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)
          python ./.github/scripts/commit/assert_commit_message.py "$HEAD_COMMIT_MESSAGE"
      - name: Assert number of commits
        run: |
          COMMITS_COUNT=${{ github.event.pull_request.commits }}
          if (( $COMMITS_COUNT > 1 )); then
            echo "Error: You have $COMMITS_COUNT commits in pull request. Squash them and keep only one."
            exit 1
          fi
      - name: Assert pull request title
        run: |
          HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)
          if [ "${{ github.event.pull_request.title }}" != "$HEAD_COMMIT_MESSAGE" ]; then
            echo "Pull request title should be the same as the commit message!"
            exit 1
          fi
