name: Pull Request verification
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:8.0.0-jdk17
    steps:
      - uses: actions/checkout@v3
      - uses: android-actions/setup-android@v2.0.10
      - uses: ./.github/actions/firebase-google-service
        with:
          secret: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
      - run: ./gradlew assemble
  tests:
    runs-on: ubuntu-latest
    container: gradle:8.0.0-jdk17
    steps:
      - uses: actions/checkout@v3
      - uses: android-actions/setup-android@v2.0.10
      - uses: ./.github/actions/firebase-google-service
        with:
          secret: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
      - run: ./gradlew test
