name: Pull Request verification
on: pull_request

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check correct branch name
        run: ./.github/scripts/branch/checkBranch.sh

  commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Check correct commit message
        run: ./.github/scripts/commit/checkCommitMessage.sh

  count-commits:
    runs-on: ubuntu-latest
    steps:
      - name: PR commits
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} ))" >> "${GITHUB_ENV}"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}
      - name: Count Commits
        run: ./.github/scripts/commit/checkCountCommits.sh "${{ env.PR_FETCH_DEPTH }}"

  lint-check:
    uses: ./.github/workflows/setup_docker_and_execute_command.yml
    with:
      command: ./gradlew lintDebug
    secrets: inherit

  ktlint-check:
    uses: ./.github/workflows/setup_docker_and_execute_command.yml
    with:
      command: ./gradlew ktlintCheck

  build:
    uses: ./.github/workflows/setup_docker_and_execute_command.yml
    with:
      command: ./gradlew assemble
    secrets: inherit

  tests:
    uses: ./.github/workflows/setup_docker_and_execute_command.yml
    with:
      command: ./gradlew test
    secrets: inherit
