name: Pull Request verification

on:
  pull_request:
    branches: '**'

jobs:

  setup_java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

  branch_name:
    needs: setup_java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Give Permission to File checkBranch.sh
        run: chmod +x ./.github/scripts/branch/checkBranch.sh
      - name: Check correct branch name
        run: ./.github/scripts/branch/checkBranch.sh

  commit_message:
    needs: setup_java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      - name: Give Permission to File checkCommitMessage.sh
        run: chmod +x ./.github/scripts/commit/checkCommitMessage.sh
      - name: Check correct commit message
        run: ./.github/scripts/commit/checkCommitMessage.sh

  build:
    needs: setup_java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check lint
        run: ./gradlew lintDebug
      - name: Check ktlint
        run: ./gradlew ktlintCheck
      - name: Build with Gradle
        run: ./gradlew build
