name: Pull Request tests
on: pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    container: gradle:8.3.0-jdk17
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-cache
      - uses: android-actions/setup-android@v2.0.10
      - uses: ./.github/actions/firebase-google-service
        with:
          secret: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
      - run: ./gradlew test
